name: Genrate ASSCI code

on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: list file
          run: ls -ltra 
        - name: Executing shell script
          run: |
            chmod +x assci1-script.sh  
            ./assci1-script.sh
        