name: Genrate ASCCII Artwork

on:
    push

jobs:
    bluid_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Excute Cowsay CMD
        run: cowsay -f animal "Run for cover, i am a Dragon...ARAW" >> animal.txt
      - name: upload animal text file
        uses: actions/upload-artifact@v4
        with:
            name: animal-text-file
            path: animal.txt
    
    test_job_2:
      needs: bluid_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download animal file
        uses: actions/download-artifact@v4
        with:
            name: aniaml-text-file

      - name: Test file exits
        run: grep -i "dragon" animal.txt
        
    deploy_job3:
      needs: [test_job_2, bluid_job_1]  
      runs-on: ubuntu-latest
      steps:
      - name: Download a dragon file
        uses: actions/download-artifact@v4
        with:
            name: aniaml-text-file

      - name: Read File
        run: cat animal.txt
      - name: Deploy
        run: echo Deploying .... ....

