name: Genrate ASCCII Artwork

on:
    push

jobs:
    bluid_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Excute Cowsay CMD
        run: cowsay -f dragon "Run for cover, i am a Dragon...ARAW" >> dragon.txt
      - name: upload dragon text file
        uses: actions/upload-artifact@v4
        with:
            name: dragon-text-file
            path: dragon.txt
    
    test_job_2:
      needs: bluid_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download a dragon file
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file

      - name: Test file exits
        run: grep -i "dragon" dragon.txt
        
    deploy_job3:
      needs: [test_job_2, bluid_job_1]  
      runs-on: ubuntu-latest
      steps:
      - name: Download a dragon file
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file

      - name: Read File
        run: cat dragon.txt
      - name: Deploy
        run: echo Deploying .... ....

